version: '3'

networks:
  my_network:
    driver: bridge

services:
  service1:
    build: C:\Git\Service1
    networks:
      - my_network

  service2:
    build: C:\Git\Service2
    networks:
      - my_network
    ports:
      - "5002:5002"

  prometheus: #Har hand om log
    image: prom/prometheus:latest #utgår från dockerlab by default
    ports:
     - "9090:9090"
    networks:
      - my_network
    volumes:
      - ./prometheus.yml/:/etc/prometheus/prometheus.yml



